name: CI
on:
  # schedule: [{cron: '0 0 * * *'}]
  push: {branches: master}
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: omelkonian/setup-agda@v0
        with:
          agda-version: 2.6.2
          stdlib-version: 1.7
          libraries: omelkonian/formal-prelude#b0d8
          main: Bitcoin
          token: ${{ secrets.GITHUB_TOKEN }}
